---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 5bee8466e67053a78761fd314e3e00e8e3c667e9
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    app: rtp-elastic-glue
    provider: fabric8
    version: 1.0.0.0
    group: rtp.demo
  name: rtp-elastic-glue
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rtp-elastic-glue
    provider: fabric8
    group: rtp.demo
